server:
  port: 80
spring:
  application:
    name: cloud-consumer-order

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: false
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka/

#开启hystrix
feign:
  hystrix:
    enabled: true

#设置feign客户端超时时间（OpenFeign集成了ribbon，超时由ribbon控制）
ribbon:
  #指的是建立连接所用的时间，适用于网络正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000